language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- 2.0.0
- rbx-2
- 2.5.1
before_install:
  - gem install bundler -v '~> 1.11'
gemfile:
  - gemfiles/40.gemfile
  - gemfiles/41.gemfile
  - gemfiles/42.gemfile
  - gemfiles/50.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/50.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/50.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/40.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/41.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/42.gemfile
cache:
  - bundler
